# Install as /etc/mosquitto/conf.d/demo-mqtt.conf
listener 8883
protocol mqtt
allow_anonymous false
password_file /etc/mosquitto/demo-passwords
acl_file /etc/mosquitto/demo-acl
certfile /etc/mosquitto/certs/server.crt
keyfile /etc/mosquitto/certs/server.key
tls_version tlsv1.2
max_packet_size 65536
