import mongoose from "mongoose";

const Schema = mongoose.Schema;

const readingSchema = new Schema({
    timestamp: { type: Date, required: true },
  C_S2: { type: Number },
  H_S6: { type: Number },
  F6: { type: Number },
  T_A2: { type: Number },
  C_S1: { type: Number },
  T_S1: { type: Number },
  H_S3: { type: Number },
  H_S5: { type: Number },
  T_S11: { type: Number },
  F5: { type: Number },
  P2_A: { type: Number },
  C_S10: { type: Number },
  T_S9: { type: Number },
  PH_S6: { type: Number },
  T_S10: { type: Number },
  PH_S1: { type: Number },
  Elv2: { type: Number },
  C_S11: { type: Number },
  T_S8: { type: Number },
  T_A4: { type: Number },
  Elv1: { type: Number },
  T_S3: { type: Number },
  F1: { type: Number },
  Elv5: { type: Number },
  PH_S10: { type: Number },
  PH_S11: { type: Number },  // Use Schema.Types.Long for large numbers
  H_A6: { type: Number },
  H_S12: { type: Number },
  PH_S7: { type: Number },
  Elv6: { type: Number },
  T_S7: { type: Number },
  F4: { type: Number },
  T_S5: { type: Number },
  H_S8: { type: Number },
  T_A6: { type: Number },
  PH_eau: { type: Number },
  H_S9: { type: Number },
  T_S12: { type: Number },
  H_A5: { type: Number },
  LEVEL_eau: { type: Number },
  T_A5: { type: Number },
  F2: { type: Number },
  H_S10: { type: Number },  // Use Schema.Types.Long for large numbers
  P1_A: { type: Number },
  C_S9: { type: Number },
  C_S8: { type: Number },
  H_A2: { type: Number },
  C_S3: { type: Number },
  H_S2: { type: Number },
  H_A3: { type: Number },
  PH_S5: { type: Number },
  T_A1: { type: Number },
  PH_S4: { type: Number },
  PH_S9: { type: Number },
  O2_A: { type: Number },
  H_S11: { type: Number },
  T_S2: { type: Number },
  H_S7: { type: Number },
  C_S12: { type: Number },
  PH_S8: { type: Number },
  H_S1: { type: Number },
  P: { type: Number },
  PH_S3: { type: Number },
  H_S4: { type: Number },
  T_A3: { type: Number },
  H_A4: { type: Number },
  PH_S12: { type: Number },
  C_S4: { type: Number },
  F3: { type: Number },
  T_S6: { type: Number },
  CO2_A: { type: Number },
  C_S7: { type: Number },
  PH_S2: { type: Number },
  C_S5: { type: Number },
  C_S6: { type: Number },
  Elv4: { type: Number },
  C: { type: Number },
  H_A1: { type: Number },
  Elv3: { type: Number },
  T_S4: { type: Number }
});

const readingModel = mongoose.model("sensor_reading", readingSchema);

export { readingModel };
